dist: xenial
os: linux
language: generic

cache:
  directories:
    - ./app/node_modules/
    - ~/.cache

addons:
  apt:
    packages:
      - libgconf-2-4 # cypress binary dependency


install:
  - cd app
  - npm ci
  - cd ..

before_script:
  # - curl https://cli-assets.heroku.com/install.sh | sh # this is for api deploy

script:
  # - bash deploy.api.sh
  # - bash build.app.sh
  - bash tests.sh

branches:
  only:
    - master
    - dev/api
    - dev/app

# deploy: # spurb.github.io/apropriacaohoras
#   local_dir: app/gh-pages
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master

# notifications:
#   webhooks: https://www.travisbuddy.com