language: node_js
node_js:
  - 12

cache:
  directories:
    - ./app/node_modules/
    - ~/.cache

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh # this is for api deploy

script:
  - bash deploy.api.sh
  - bash build.app.sh

branches:
  only:
    - master
    - dev/api
    - dev/app

deploy: # spurb.github.io/apropriacaohoras
  local_dir: app/gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

notifications:
  webhooks: https://www.travisbuddy.com