dist: xenial
os: linux
language: shell

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh

script: bash deploy.api.sh
branches:
  only:
    - master
    - stagging/api

deploy:
  local_dir: app/dist
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master